version: '3.8'
services:
  app:
    container_name: tpg_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: tpg_db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./migrations/postgres:/migrations  # Mount the directory containing migrations
    command: [ "-path", "/migrations", "-database", "postgres://${POSTGRES_DB_USER}:${POSTGRES_DB_PASS}@tpg_db:5432/${POSTGRES_DB_NAME}?sslmode=disable", "up" ]