CREATE TABLE IF NOT EXISTS products
(
    id               INT GENERATED BY DEFAULT AS IDENTITY,
    guid             UUID      default uuid_generate_v4() NOT NULL,
    name             TEXT                                 NOT NULL,
    price            BIGINT                               NOT NULL,
    created_at       TIMESTAMP default now(),
    last_modified_at TIMESTAMP,
    deleted_at       TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE (guid)
);

INSERT INTO products(name, price) VALUES ('product 1', 50000), ('product 2', 100000);