CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users
(
    id                    INT GENERATED BY DEFAULT AS IDENTITY,
    guid                  UUID      default uuid_generate_v4() NOT NULL,
    email                 TEXT                                 NOT NULL,
    password              TEXT                                 NOT NULL,
    created_at            TIMESTAMP default now(),
    last_modified_at      TIMESTAMP,
    deleted_at            TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE (email)
);



